language: php  # specify your language
php: # specify options for your language
  # using major version aliases
- 5.6
- 7.0
- 7.1

install:
  - composer install

before_script:
  - mkdir -p build/logs  
  
script: vendor/bin/phpunit --configuration "$PWD/test/phpunit.xml" --coverage-text

after_success:
  - travis_retry php vendor/bin/coveralls -v