<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zend\ServiceManager\ServiceLocatorAwareTrait' => __DIR__ . '/src/Zend/ServiceManager/ServiceLocatorAwareTrait.php',
    'Zend\ServiceManager\ServiceLocatorAwareInterface' => __DIR__ . '/src/Zend/ServiceManager/ServiceLocatorAwareInterface.php',
    'Zend3Helper\Module' => __DIR__ . '/src/Module.php',
);
