<?php

namespace MNHcC\Zend3bcHelper\ServiceManager;
use MNHcC\Zend3bcHelper\Testing\ServiceManager\AbstractBcFactoryImplementation;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-25 at 17:15:30.
 */
class AbstractBcFactoryTest extends \Zend\Test\PHPUnit\Controller\AbstractControllerTestCase {

    /**
     * @var AbstractBcFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        parent::setup();
        $this->object = new AbstractBcFactoryImplementation();
        var_dump($this->getApplicationConfig()); 
        
        $config = include 'test/config/application.config.php';
        if (class_exists(\Zend\Router\Module::class)) {
            $config['modules'][] = \Zend\Router::class;
        }     
        $this->setApplicationConfig($config);
        $this->getApplicationServiceLocator()->setFactory('testService', AbstractBcFactoryImplementation::class);
        
    }

    /**
     * @covers MNHcC\Zend3bcHelper\ServiceManager\AbstractBcFactory::__invoke
     */
    public function test__invoke() {
        $object = $this->object;
        $this->assertInstanceOf(\stdClass::class, $object($this->getApplicationServiceLocator(), 'testService'));
    }
    
    /**
     * @covers MNHcC\Zend3bcHelper\ServiceManager\AbstractBcFactory::createService
     */
    public function testCreateService() {
        $this->assertInstanceOf(\stdClass::class, $this->object->createService($this->getApplicationServiceLocator()));
    }
    
    public function testWorkingOnServiceLocator() {
      $this->assertInstanceOf(\stdClass::class, $this->getApplicationServiceLocator()->get('testService'));
    }
}
