<?php

namespace MNHcC\Zend3bcHelper\Testing\ServiceManager;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-25 at 17:15:30.
 */
class AbstractBcFactoryImplementation extends \MNHcC\Zend3bcHelper\ServiceManager\AbstractBcFactory {
    
    /**
     * createService method for testing the AbstractBcFactory
     * @param \Zend\ServiceManager\ServiceLocatorInterface $serviceLocator
     * @return \stdClass
     */
    public function createService(\Zend\ServiceManager\ServiceLocatorInterface $serviceLocator) {
        return new \stdClass();
    }

}
