<?php

namespace MNHcC\Zend3bcHelper\Helper;

use Zend;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-25 at 14:51:47.
 */
class AbstractTypeHelperTest extends Zend\Test\PHPUnit\Controller\AbstractControllerTestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MNHcC\Zend3bcHelper\Helper\AbstractTypeHelper::isZend3bcHelperClass
     * @todo   Implement testIsZend3bcHelperClass().
     */
    public function testIsZend3bcHelperClass() {
        // Remove the following lines when you implement this test.
        $this->assertTrue(AbstractTypeHelper::isZend3bcHelperClass(AbstractTypeHelper::class));
    }

    /**
     * @covers MNHcC\Zend3bcHelper\Helper\AbstractTypeHelper::wichZendMvcMajor
     * @todo   Implement testWichZendMvcMajor().
     */
    public function testWichZendMvcMajor() {
        // Remove the following lines when you implement this test.
        $this->assertContains(AbstractTypeHelper::wichZendMvcMajor(),[2,3]);
    }

}
