<?php
// Generated by MNHcC\Zend3bcHelper's ./bin/classmap_generator.php (forked from Zend Framework 2) 
return [
    \Zend\ServiceManager\ServiceLocatorAwareInterface::class => __DIR__ . DIRECTORY_SEPARATOR .'Zend' . DIRECTORY_SEPARATOR . 'ServiceManager' . DIRECTORY_SEPARATOR . 'ServiceLocatorAwareInterface.php',
    \Zend\ServiceManager\ServiceLocatorAwareTrait::class     => __DIR__ . DIRECTORY_SEPARATOR .'Zend' . DIRECTORY_SEPARATOR . 'ServiceManager' . DIRECTORY_SEPARATOR . 'ServiceLocatorAwareTrait.php',
    \MNHcC\Zend3bcHelper\Module::class                       => __DIR__ . DIRECTORY_SEPARATOR .'Module.php',
];
