<?php
// Generated by MNHcC\Zend3bcHelper's ./bin/classmap_generator.php
return [
    'Zend\ServiceManager\ServiceLocatorAwareTrait'     => __DIR__ . '/Zend/ServiceManager/ServiceLocatorAwareTrait.php',
    'Zend\ServiceManager\ServiceLocatorAwareInterface' => __DIR__ . '/Zend/ServiceManager/ServiceLocatorAwareInterface.php',
    'MNHcC\Zend3bcHelper\Module'                       => __DIR__ . '/Module.php',
];
